###### Types of Encoding #####

1. Label Encoding
   
    1.Ordinal or Simple Categories

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/User/Desktop/Poonam FBS/Data Science/Datasets/cars93.csv")
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [3]:
df['AirBags'].unique()

array(['Driver only', 'Driver & Passenger', nan], dtype=object)

In [4]:
df['AirBags'].mode()

0    Driver only
Name: AirBags, dtype: object

In [5]:
df['AirBags'] = df['AirBags'].fillna('Driver only')

In [6]:
df['AirBags'].unique()

array(['Driver only', 'Driver & Passenger'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
data = le.fit_transform(df['AirBags'])
data

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0])

In [10]:
#add this data into dataframe

print(type(data))
print(data.shape)

<class 'numpy.ndarray'>
(93,)

In [11]:
df['AirBags_Encoded'] = data

In [12]:
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room,AirBags_Encoded
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0,1
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0,0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0,1
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0,0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0,1
...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,NaN,0
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0,0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0,0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0,1
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0,0

2. One Hot Encoding

In [13]:
#Pandas
data = pd.get_dummies(df['AirBags'])
data

    Driver & Passenger  Driver only
0                False         True
1                 True        False
2                False         True
3                 True        False
4                False         True
..                 ...          ...
88                True        False
89                True        False
90                True        False
91               False         True
92                True        False

[93 rows x 2 columns]

In [14]:
#Pandas
data = pd.get_dummies(df['AirBags'], dtype =int)
data

    Driver & Passenger  Driver only
0                    0            1
1                    1            0
2                    0            1
3                    1            0
4                    0            1
..                 ...          ...
88                   1            0
89                   1            0
90                   1            0
91                   0            1
92                   1            0

[93 rows x 2 columns]

In [15]:
#sklearn
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe = OneHotEncoder()
ohe.fit_transform(df[['AirBags']]).toarray()

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [17]:
ohe = OneHotEncoder(sparse_output = False)
d  = df['AirBags'].unique()

In [18]:
d.sort()
d

array(['Driver & Passenger', 'Driver only'], dtype=object)

In [19]:
data = pd.DataFrame(ohe.fit_transform(df[['AirBags']]), columns = d, dtype=int)
data.head()

   Driver & Passenger  Driver only
0                   0            1
1                   1            0
2                   0            1
3                   1            0
4                   0            1

In [20]:
df2 = df.drop('AirBags', axis=1)

In [21]:
df2.head()

,Manufacturer,Model,Type,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room,AirBags_Encoded
0,Acura,Integra,Small,15.9,25,140,5,26.5,11.0,1
1,Acura,Legend,Midsize,33.9,18,200,5,30.0,15.0,0
2,Audi,90,Compact,29.1,20,172,5,28.0,14.0,1
3,Audi,100,Midsize,37.7,19,172,6,31.0,17.0,0
4,BMW,535i,Midsize,30.0,22,208,4,27.0,13.0,1

In [22]:
df2 = pd.concat([df2, data], axis=1)
df2.head()

,Manufacturer,Model,Type,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room,AirBags_Encoded,Driver & Passenger,Driver only
0,Acura,Integra,Small,15.9,25,140,5,26.5,11.0,1,0,1
1,Acura,Legend,Midsize,33.9,18,200,5,30.0,15.0,0,1,0
2,Audi,90,Compact,29.1,20,172,5,28.0,14.0,1,0,1
3,Audi,100,Midsize,37.7,19,172,6,31.0,17.0,0,1,0
4,BMW,535i,Midsize,30.0,22,208,4,27.0,13.0,1,0,1

### Orinal Encoder

In [23]:
#Ordinalencoder

In [24]:
df['Type']

0       Small
1     Midsize
2     Compact
3     Midsize
4     Midsize
       ...
88        Van
89    Compact
90     Sporty
91    Compact
92    Midsize
Name: Type, Length: 93, dtype: object

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room,AirBags_Encoded
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0,1
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0,0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0,1
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0,0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0,1

In [27]:
df['Type'].unique()

array(['Small', 'Midsize', 'Compact', 'Large', 'Sporty', 'Van'],
      dtype=object)

In [28]:
#df['type'].unique()
oe = OrdinalEncoder(categories=[['Compact', 'Small', 'Midsize', 'Large', 'Sporty', 'Van']])
oe.fit_transform(df[['Type']]).astype('int')

array([[1],
       [2],
       [0],
       [2],
       [2],
       [2],
       [3],
       [3],
       [2],
       [3],
       [2],
       [0],
       [0],
       [4],
       [2],
       [5],
       [5],
       [3],
       [4],
       [3],
       [0],
       [3],
       [1],
       [1],
       [0],
       [5],
       [2],
       [4],
       [1],
       [3],
       [1],
       [1],
       [0],
       [4],
       [4],
       [5],
       [2],
       [3],
       [1],
       [4],
       [4],
       [1],
       [0],
       [1],
       [1],
       [4],
       [2],
       [2],
       [2],
       [2],
       [2],
       [3],
       [1],
       [1],
       [0],
       [5],
       [4],
       [0],
       [2],
       [4],
       [2],
       [1],
       [2],
       [1],
       [0],
       [5],
       [2],
       [0],
       [2],
       [5],
       [3],
       [4],
       [1],
       [0],
       [4],
       [2],
       [3],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [4],
       [2],
       [5],
       [1],
       [5],
       [0],
       [4],
       [0],
       [2]])