Sudents marks for 20 students with  6 subjects , gain marks , percentage
1. Create dataframe for 20 students marks

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
df = pd.DataFrame(np.random.randint(30,100,(20,6)) , columns = ['Subject 1', 'Subject 2','Subject 3', 'Subject 4' ,'Subject 5' , 'Subject 6'])
df

    Subject 1  Subject 2  Subject 3  Subject 4  Subject 5  Subject 6
0          94         34         40         82         66         68
1          63         96         32         49         68         87
2          89         97         77         95         43         32
3          34         86         46         49         84         94
4          99         45         63         71         46         58
5          45         52         53         64         61         94
6          44         95         82         68         88         70
7          80         33         69         35         53         89
8          79         99         68         62         74         44
9          99         32         66         57         45         98
10         50         60         48         82         92         71
11         36         44         66         45         67         62
12         98         72         51         53         34         84
13         79         62         63         90         36         40
14         72         59         60         61         34         48
15         46         50         68         97         59         74
16         55         47         44         43         62         56
17         87         78         36         66         96         56
18         85         77         89         70         37         95
19         84         93         80         42         42         70

In [10]:
# sub1 = np.random.randint(30,100,20)
# sub2 = np.random.randint(30,100,20)


# df2 = pd.DataFrame({'Subject 1' : sub1 , 'Subject 2' : sub2})
# df2

In [14]:
# df['Gain Marks'] = df['Subject 1'] + df['Subject 2'] + df['Subject 3'] + df['Subject 4'] + df['Subject 5'] + df['Subject 6']
# df

In [16]:
df['Gain Marks'] = df[['Subject 1','Subject 2', 'Subject 3', 'Subject 4', 'Subject 5', 'Subject 6']].sum(axis = 1)
df

,Subject 1,Subject 2,Subject 3,Subject 4,Subject 5,Subject 6,Gain Marks,Percentage
0,94,34,40,82,66,68,384,64.000000
1,63,96,32,49,68,87,395,65.833333
2,89,97,77,95,43,32,433,72.166667
3,34,86,46,49,84,94,393,65.500000
4,99,45,63,71,46,58,382,63.666667
5,45,52,53,64,61,94,369,61.500000
6,44,95,82,68,88,70,447,74.500000
7,80,33,69,35,53,89,359,59.833333
8,79,99,68,62,74,44,426,71.000000
9,99,32,66,57,45,98,397,66.166667
10,50,60,48,82,92,71,403,67.166667
11,36,44,66,45,67,62,320,53.333333
12,98,72,51,53,34,84,392,65.333333
13,79,62,63,90,36,40,370,61.666667
14,72,59,60,61,34,48,334,55.666667
15,46,50,68,97,59,74,394,65.666667
16,55,47,44,43,62,56,307,51.166667
17,87,78,36,66,96,56,419,69.833333
18,85,77,89,70,37,95,453,75.500000
19,84,93,80,42,42,70,411,68.500000

In [12]:
df.head()

,Subject 1,Subject 2,Subject 3,Subject 4,Subject 5,Subject 6,Gain Marks
0,94,34,40,82,66,68,384
1,63,96,32,49,68,87,395
2,89,97,77,95,43,32,433
3,34,86,46,49,84,94,393
4,99,45,63,71,46,58,382

In [13]:
df['Percentage'] = df['Gain Marks'] / 600 * 100
df

,Subject 1,Subject 2,Subject 3,Subject 4,Subject 5,Subject 6,Gain Marks,Percentage
0,94,34,40,82,66,68,384,64.000000
1,63,96,32,49,68,87,395,65.833333
2,89,97,77,95,43,32,433,72.166667
3,34,86,46,49,84,94,393,65.500000
4,99,45,63,71,46,58,382,63.666667
5,45,52,53,64,61,94,369,61.500000
6,44,95,82,68,88,70,447,74.500000
7,80,33,69,35,53,89,359,59.833333
8,79,99,68,62,74,44,426,71.000000
9,99,32,66,57,45,98,397,66.166667
10,50,60,48,82,92,71,403,67.166667
11,36,44,66,45,67,62,320,53.333333
12,98,72,51,53,34,84,392,65.333333
13,79,62,63,90,36,40,370,61.666667
14,72,59,60,61,34,48,334,55.666667
15,46,50,68,97,59,74,394,65.666667
16,55,47,44,43,62,56,307,51.166667
17,87,78,36,66,96,56,419,69.833333
18,85,77,89,70,37,95,453,75.500000
19,84,93,80,42,42,70,411,68.500000